### PR TITLE
Added support for JSON-LD 1.1 @json @type

### PR DESCRIPTION
**Pull request by umbreak**
Added support for [Json literal](https://www.w3.org/TR/json-ld11/#dfn-json-literal)

I've added the tests from the current test suite related to JSON literal. The only test that doesn't pass (which I remove from the manifest) is `toRdf-js12`. An unicode code point `\u00F` is meant to be lowercased to `\u00f`.

### CODE REVIEW

**Comment by dr0i** [comment]
Hi @umbreak , I don't know if your are aware of https://github.com/jsonld-java/jsonld-java/pull/283, also https://github.com/jsonld-java/jsonld-java/pull/284#issuecomment-653521148. I think there are some redundancies to ypur PR.
 I don't know how, or if, we proceed on this.

**Comment by umbreak** [comment]
That branch is an attempt to fully support of 1.1. I was hoping for a more iterative approach here where only some features are introduced.

But I understand if you don't see it the same way.

**Comment by fsteeg** [comment]
> The branch you are referring me to is an attempt to fully support of 1.1. I was hoping for a more iterative approach here where only some features are introduced

This was exactly my intention with that setup, see https://github.com/jsonld-java/jsonld-java/pull/277#issue-351389246:

> I think that with this setup, we can keep releasing from master whenever the build passes, while making available the 1.1 support that we currently have.

Maybe we should follow up on the suggestion by @ansell in https://github.com/jsonld-java/jsonld-java/pull/283#issuecomment-623045793 and merge https://github.com/jsonld-java/jsonld-java/pull/283 into `develop`, and move on from there (e.g. rebasing this on `develop`).

**Comment by umbreak** [comment]
I'm fine with that approach too. Once you merge #283 into `develop` branch I can put this functionality in that branch.

**Comment by dr0i** [comment]
I merged  #283 into the develop branch.
@umbreak as you proposed, you may go on and put the functionality into a PR against that develop branch.

**Comment by umbreak** [comment]
Done in the develop branch

**Pull request closed without merging**
