### PR TITLE
This should fix issue #262

### PR DESCRIPTION
**Pull request by RinkeHoekstra**
* Included new JSON-LD tests in json-ld.org directory (perhaps rename this to something more W3C specific, as these are the latest tests from W3C)
* Updated `core/src/test/java/com/github/jsonldjava/core/JsonLdProcessorTest.java` to start from `manifest.jsonld` rather than all jsonld files in the test directory; then iterating of the the list of manifest files specified there.

### CODE REVIEW

**Comment by fsteeg** [comment]
Hi @RinkeHoekstra, thanks for your pull request! Some thoughts:

- It looks like the email used in your local Git config is not known to GitHub, so your commit here is not connected to your account
- Your changes are conflicting with the current master branch due to changes in master after you branched off. You should merge the current master into your branch or rebase your branch on top of the current master, and resolve the conflicts (in toRdf-manifest.jsonld)
- If you mention the related issue in the initial pull request comment (as you did in the commit), a useful link to the pull request is created in the issue
- We should not keep commented-out code around, it's in the Git history so we can always check that if we need the old code
- I'm not sure if it's a good idea to include a copy of the test suites in our repo. Maybe we could go with the approach that jsonld.js takes, which is to expect local checked out repos for the tests (and as a second step, automate checking out these repos), see https://github.com/digitalbazaar/jsonld.js/#tests
- As many of these tests currently fail with our implementation, we need a way to specify which tests to skip, like the `skip` entries in https://github.com/digitalbazaar/jsonld.js/blob/master/tests/test-common.js. Perhaps for this pull request, you could make running against the new suite an option, and we keep running the old suite as the default. As a next step we can then implement skipping specific tests, and then switch the default to the new suite.

@ansell: Any thoughts on this, in particular about the last two points?

**Comment by ansell** [comment]
@fsteeg I haven't had a chance to review the code changes. Getting the testsuite up to what the rest of the JSON-LD community are using is a good thing.

I like tests in this repository, it gives consistent builds. Nothing worse than having to check out another repository and then rely on it being stable. Having a script to sync them when changes are made upstream would be ideal, but not necessary for this pull request.

I don't mind having broken upstream compliance tests on master while they are being worked through, but I haven't seen the degree to which they are failing due to implementation deficiencies here. I wouldn't be surprised if quite a few are failing, given the lack of attention that Tristan and I have been able to give to this codebase over the past few years. If too many are broken I will do a release before merging, given the few minor changes since the last release.

**Comment by ansell** [comment]
@RinkeHoekstra As Fabian says, the git commit metadata is important to track who is contributing here. We have automated cleanup for code formatting, so don't worry about that too much, but removing commented out code that is being replaced is a good thing.

**Comment by ansell** [comment]
There are too many failing tests with similar errors to pull this into master at this point. Many of them seem to have similar reasons which should be fairly easy to fix as part of this Pull Request, to isolate those that are genuinely failing due to an out of date implementation or a lack of implementation for new features.

`JsonLd invalid term definition: 1.1` and `java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String` are two errors that appear often in the results and probably should be investigated before merging this.

```
[ERROR] Tests run: 929, Failures: 204, Errors: 220, Skipped: 12
```

**Comment by fsteeg** [comment]
Pushed some smaller changes to handle some 1.1 constructs.

Doesn't help much (+25 passing tests total), but moves many errors to failures:

> [ERROR] Tests run: 929, Failures: 293, Errors: 106, Skipped: 12

**Comment by dsemenovsky** [comment]
Hey @fsteeg @ansell @RinkeHoekstra

**Comment by fsteeg** [comment]
@dsemenovsky Thanks for offering help. If you need any specific 1.1 features you could let us know, so we can focus on implementing them first, and you could test the implementation.

**Comment by fsteeg** [comment]
Added support for JSON literals. Current state: 

```
[ERROR] Tests run: 929, Failures: 296, Errors: 80, Skipped: 12
```

**Comment by fsteeg** [comment]
Added different 1.1 tweaks and fixes in https://github.com/jsonld-java/jsonld-java/pull/265/commits/906cdefaa8773db4e5798c67ada7c61562fa01e2, current state:

```
[ERROR] Tests run: 930, Failures: 355, Errors: 14, Skipped: 12
```

I've also set up an option to run the old 1.1 suite in my fork (https://github.com/fsteeg/jsonld-java/commit/278dce3e58069fb1bd7d44009a481b3481ea60b7), which currently also has a lot of failures. In jsonld.js they support that option too (see bottom of https://github.com/digitalbazaar/jsonld.js/#tests), however these tests fail over there too, so I'm not sure if it makes sense to set that up here.

In any case I'd suggest we rename the test suite folder in this branch to `json-ld-api-tests` to avoid confusion with the old `json-ld.org` suite.

**Comment by fsteeg** [comment]
Replaced by / moved to https://github.com/jsonld-java/jsonld-java/pull/283 & https://github.com/jsonld-java/jsonld-java/pull/284, closing.

**Pull request closed without merging**
