### PR TITLE
Current state of 1.1 development

### PR DESCRIPTION
**Pull request by fsteeg**
As announced in https://github.com/jsonld-java/jsonld-java/pull/277#issuecomment-611497707, this PR contains the current functional changes for 1.1.

It also contains comments by @gkellogg from https://github.com/gkellogg/jsonld-java/commit/53aa216e8e67d56454b59a4b74dc1cf994ec4148 (thanks!)

The diff on `core/reports/json-ld-api-tests-skip` shows the progress compared to the `1.1-tests` branch (currently 94 removed lines, i.e. 94 additional passing tests). See individual commits for details on which code changes make which tests pass. Open the URLs for test details.

This is the report summary for 1.1 compliance with the current code (see https://github.com/jsonld-java/jsonld-java/commit/23183764a23da09106fadf837c8556a43bb54c6b):

tests | pass
-- | --
Compaction | 101/238 (42.4%)
Expansion | 124/366 (33.9%)
Flattening | 45/55 (81.8%)
Framing | 26/89 (29.2%)
HTML | 3/49 (6.1%)
Remote document | 3/18 (16.7%)
Transform JSON-LD to RDF | 178/442 (40.3%)
Transform RDF to JSON-LD | 39/51 (76.5%)

The base for this PR is set to `1.1-tests` for a reviewable diff (i.e. merge into master after https://github.com/jsonld-java/jsonld-java/pull/283).

### CODE REVIEW

**Comment by fsteeg** [comment]
I just discovered that there is a new Java implementation for JSON-LD 1.1, titanium-json-ld: https://github.com/filip26/titanium-json-ld. It is linked from https://json-ld.org/ and included in the conformance report at https://w3c.github.io/json-ld-api/reports/. Given the amount of work still required here, and the level of conformance already achieved by titanium-json-ld, I'm wondering if it actually makes sense to continue our effort here.

**Comment by ansell** [comment]
I have not had time to put into this project recently. If the JSON-LD 1.1 changes are not progressing well, then that may be an option. I am merging this into the 1.1 branch based on Travis passing.

**Comment by umbreak** [comment]
I did some [benchmarks of both implementations](https://github.com/umbreak/jsonld-benchmarks#results) and Json-LD Java is by fr more performant.

As I mentioned on the repo it is very well just probably due to the fact that the Json-LD 1.1 spec is more complex and not to the titanium codebase. However it is good to keep track of it

**Comment by gkellogg** [comment]
> I did some [benchmarks of both implementations](https://github.com/umbreak/jsonld-benchmarks#results) and Json-LD Java is by fr more performant.
> 
> As I mentioned on the repo it is very well just probably due to the fact that the Json-LD 1.1 spec is more complex and not to the titanium codebase. However it is good to keep track of it

Depending on which algorithms are involved, for 1.0-like data, the added complexity shouldn't really impact performance. There are some additional checks to look for scoped contexts in expansion and compaction, and for different container types, but I wouldn't expect these to have any significant affect on basic performance if these features aren't used.

A healthy eco-system depends on diverse implementations, and I hope that jsonld-java continues to make progress towards full 1.1 conformance.

**Pull request merged**
