### PR TITLE
Tests and setup for 1.1 development

### PR DESCRIPTION
**Pull request by fsteeg**
I suggest this to resolve https://github.com/jsonld-java/jsonld-java/issues/262.

I've been looking some more into what I mentioned in https://github.com/jsonld-java/jsonld-java/pull/265#issuecomment-562577767 and I think this is a good way to avoid both regressions while working on 1.1 features, and a long running 1.1 branch:

- The original contribution by @RinkeHoekstra in https://github.com/jsonld-java/jsonld-java/commit/24a56c391811396956a50a987e5859c83da80b0d (https://github.com/jsonld-java/jsonld-java/pull/265): switch to json-ld-api test suite
- Add support for running the json-ld-framing test suite and the original 1.0 test suite (`mvn test` runs only the original 1.0 suite, `mvn -Dtest=AllSuites test` runs all 3 suites)
- Add support for some 1.1 features (see commits for details, https://github.com/jsonld-java/jsonld-java/commit/0f439dcaadb78fbc59616c2cfc91be6dd67dcb88 & https://github.com/jsonld-java/jsonld-java/commit/7aeae88ea571ed9bbce02f71d1da1a95bc660ce1 resolve https://github.com/jsonld-java/jsonld-java/issues/263)

I think that with this setup, we can keep releasing from master whenever the build passes, while making available the 1.1 support that we currently have.

### CODE REVIEW

**Comment by fsteeg** [comment]
Added setup for skipping tests in https://github.com/jsonld-java/jsonld-java/pull/277/commits/79fdafa1b6fe3d1486b1b58d339f81e01bb0e4f3 (before this, coverage went down, now it's up).

- Skip only failing tests to make sure we run 1.1 code paths in CI
- Use resolvable URLs in skip files, they can act like TODO lists
- Delete `*-skip` files to re-generate them during next test run

Now `mvn test` runs all tests that are not listed in the files.

**Comment by dr0i** [comment]
I think this is could be a good starting point to implement json-ld 1.1 step-by-step. What do you think @ansell ?

**Comment by fsteeg** [comment]
To clarify what this does compared to the current test setup in master:

- Run all original 1.0/master tests (nothing skipped here)
- Additionally run the [lson-ld-api tests](https://github.com/w3c/json-ld-api/blob/master/tests/README.md) in [test/resources/json-ld-api-tests](https://github.com/jsonld-java/jsonld-java/tree/10ee2aab46e28e85f0e62e54a4c996c07690e045/core/src/test/resources/json-ld-api-tests)
- Additionally run the [lson-ld-framing tests](https://github.com/w3c/json-ld-framing/blob/master/tests/README.md) in [test/resources/json-ld-framing-tests](https://github.com/jsonld-java/jsonld-java/tree/10ee2aab46e28e85f0e62e54a4c996c07690e045/core/src/test/resources/json-ld-framing-tests)

For all of these:

- If there is no `reports/*-skip` file  (e.g. `reports/json-ld-api-tests-skip`), run all tests, writing failing tests URIs (e.g. https://w3c.github.io/json-ld-api/tests/compact-manifest.html#t0037) to a file
- If there is such a file, skip all tests listed in that file
- State of skipped tests in this branch is 0 (of 472) for [1.0](https://github.com/jsonld-java/jsonld-java/blob/10ee2aab46e28e85f0e62e54a4c996c07690e045/core/reports/json-ld-1.0-tests-skip), 366 (of 805) for [1.1-api](https://github.com/jsonld-java/jsonld-java/blob/10ee2aab46e28e85f0e62e54a4c996c07690e045/core/reports/json-ld-api-tests-skip), and 59 (of 86) for [1.1-framing](https://github.com/jsonld-java/jsonld-java/blob/10ee2aab46e28e85f0e62e54a4c996c07690e045/core/reports/json-ld-framing-tests-skip)

The propsed workflow towards 1.1 would be:

- Merge this into master, keep releasing from master, because all current master tests still work
- When implementing new 1.1 features, pick an entry from a skip file (e.g. https://w3c.github.io/json-ld-api/tests/compact-manifest.html#t0037 from [1.1-api](https://github.com/jsonld-java/jsonld-java/blob/10ee2aab46e28e85f0e62e54a4c996c07690e045/core/reports/json-ld-api-tests-skip)), implement suport for that test case
- Remove the `reports/*-skip` file, rerun tests to regenerate a (hopefully) smaller skip file, with less tests to skip, and commit changed skip file together with the implementation

**Comment by fsteeg** [comment]
A quick status update: I've pushed some tweaks to the tests and report setup, updated the tests and looked into integrating with https://w3c.github.io/json-ld-api/reports/ (see https://github.com/jsonld-java/jsonld-java/pull/277/commits/6f1eb6c0f924a6423a1678a4321a7040b02daf44). With current spec tests and implementation (`master` + `1.1`) we currently get this test suite compliance summary:

tests | pass
-- | --
Compaction | 99/238 (41.6%)
Expansion | 124/366 (33.9%)
Flattening | 45/55 (81.8%)
Framing | 26/89 (29.2%)
HTML | 3/49 (6.1%)
Remote document | 3/18 (16.7%)
Transform JSON-LD to RDF | 178/442 (40.3%)
Transform RDF to JSON-LD | 39/51 (76.5%)

I discussed our next steps with @dr0i and we think we should split up this branch/PR into two branches: one for the changes in the test setup only (`1.1-tests`) and one, branched off from the first, with implementation changes only (`1.1`). That way, we hope we'll avoid a giant, un-reviewable PR while working towards 1.1 compliance.

**Comment by gkellogg** [comment]
Any report would be a good start; you can always submit an update and we can regenerate the report.

Time permitting, I'll have a look at your code and offer some suggestions for improving conformance.

**Comment by fsteeg** [comment]
Replaced by / moved to https://github.com/jsonld-java/jsonld-java/pull/283 & https://github.com/jsonld-java/jsonld-java/pull/284, closing.

**Pull request closed without merging**
