### PR TITLE
Added support for @default inside sets

### LINKED ISSUE #167: Support "@default" inside properties in framing when using sets
## Frame

```
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "ex": "http://example.org/vocab#"
  },
  "@type": "ex:Library",
  "ex:contains": {
    "@explicit":true,
    "dc:title":{"@default":"Title missing"},
    "dc:creator":{}
  }
}

```

 ## Data

```
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "ex": "http://example.org/vocab#"
  },
  "@graph": [
    {
      "@id": "http://example.org/library",
      "@type": "ex:Library",
      "ex:contains": [{"@id":"http://example.org/library/the-republic#introduction"},{"@id":"http://example.org/library/the-republic"}]
    },
    {
      "@id": "http://example.org/library/the-republic",
      "@type": "ex:Book",
      "dc:creator": "Plato",
      "dc:title": "The Republic"
    },
    {
      "@id": "http://example.org/library/the-republic#introduction",
      "@type": "ex:Book",
            "dc:creator": "Plato"
    }
  ]
}
```

 ## Expected result
```
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "ex": "http://example.org/vocab#"
  },
  "@graph": [
    {
      "@id": "http://example.org/library",
      "@type": "ex:Library",
      "ex:contains": [
        {
          "@id": "http://example.org/library/the-republic#introduction",
          "@type": "ex:Book",
          "dc:creator": "Plato",
          "dc:title": "Title missing"
        },
        {
          "@id": "http://example.org/library/the-republic",
          "@type": "ex:Book",
          "dc:creator": "Plato",
          "dc:title": "The Republic"
        }
      ]
    }
  ]
}
```

 ## Actual result
```
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "ex": "http://example.org/vocab#"
  },
  "@graph": [
  {
    "@id": "http://example.org/library",
    "@type": "ex:Library",
    "ex:contains": {
      "@id": "http://example.org/library/the-republic",
      "@type": "ex:Book",
      "dc:creator": "Plato",
      "dc:title": "The Republic"
    }
  }
]
}



```

### PR DESCRIPTION
**Pull request by hmottestad**
Fix #167

### CODE REVIEW

**Comment by ansell** [comment]
I have had an introductory look at this, but I don't fully understand the rationale so I am waiting for when I have some time spare to work through what the framing spec says on this issue. Any pointers to places that describe this situation in the spec would be appreciated.

**Comment by hmottestad** [comment]
@ansell I don't know if it's in the spec per say, I have found the spec rather difficult to understand to be honest. But the test case I wrote works in the jsonld playground online, but doesn't work in the java program.

**Comment by hmottestad** [comment]
It's been almost a month since I created this patch. @ansell Have you had a chance to look at it yet?

The fix is for using ´@default´ on a property inside a set. Which is not supported in the current implementation. I have tested it in the json-ld playground, and it works fine there.

An example frame:

```
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "ex": "http://example.org/vocab#"
  },
  "@type": "ex:Library",
  "ex:contains": {
    "@explicit":true,
    "dc:title":{"@default":"Title missing"},
    "dc:creator":{}
  }
}
```

The `"dc:title":{"@default":"Title missing"},` property is ignored in the current implementation.

Maybe the first thing you should consider @ansell is if ´@default´ is supposed to work inside a set.

**Comment by ansell** [comment]
Given that the current draft version of the spec is unclear on where @default may not be used (if anywhere), I have to assume that it can be used here, and as you say it works in the reference JSONLD Playground.

Thanks for the patch. Sorry for the delay, have been busy recently.

**Comment by ansell** [comment]
Released jsonld-java-0.8.3 with this fix in it, should be on Maven Central in a few hours

**Pull request merged**
