### PR TITLE
Support `pruneBlankNodeIdentifiers` framing option in 1.1 mode

### PR DESCRIPTION
**Pull request by fsteeg**
See https://json-ld.org/spec/latest/json-ld-framing/#jsonldoptions & https://github.com/json-ld/json-ld.org/issues/293

### CODE REVIEW

**Comment by eroux** [comment]
@ansell do you think this could be merged, or if not, maybe you have some ideas of improvements?

**Comment by ansell** [comment]
Looks good and tests are passing on Travis, so merging it in. Thanks @fsteeg

**Comment by eroux** [comment]
Starting to work on another issue, I realize https://json-ld.org/test-suite/ has some tests about pruning blank nodes (under *Framing Tests*: `Test p010`, `Test p020`, `Test p021`, `Test p046` and `Test p049`), @fsteeg maybe you could add them?

**Comment by fsteeg** [comment]
Thanks for the pointer @eroux. I've added the tests and fixed an issue in the implementation exposed by one of the tests in https://github.com/jsonld-java/jsonld-java/pull/209. I did not add `p049` since both the pruning and non-pruning versions fail (unimplemented 1.1 feature?).

**Pull request merged**
